---
- name: Ensure gatus config dir
  ansible.builtin.file:
    path: /opt/gatus_config
    mode: "644"
    state: directory

- name: Ensure gatus data dir
  ansible.builtin.file:
    path: /opt/gatus_data
    mode: "644"
    state: directory

- name: Ensure gatus env dir
  ansible.builtin.file:
    path: /opt/gatus_env
    mode: "644"
    state: directory

- name: Ensure doll report config dir
  ansible.builtin.file:
    path: /opt/doll.report.nginx.conf.d
    state: directory
    mode: "644"

- name: Create doll-report docker network
  community.docker.docker_network:
    enable_ipv6: true
    name: doll-report
    ipam_config:
      - subnet: fd00:babe:cafe::/64

- name: Instance defined dashboards
  ansible.builtin.include_tasks: dashboard_instance.yaml
  vars:
    dashboard_name: "{{ ( (filename | split('/') )[-1] | split('.') )[0] }}"
  with_fileglob:
    - "dashboards/*"
  loop_control:
    loop_var: filename
  when: dashboard_list is undefined

- name: Instance defined dashboards
  ansible.builtin.include_tasks: dashboard_instance.yaml
  vars:
    dashboard_name: "{{ ( (filename | split('/') )[-1] | split('.') )[0] }}"
  loop: "{{ dashboard_list }}"
  loop_control:
    loop_var: filename
  when: dashboard_list is defined

- name: Ensure nginx aggregator container
  community.docker.docker_container:
    name: "nginx-doll-report"
    image: nginx:latest
    state: started
    restart_policy: "unless-stopped"
    restart: true
    recreate: false
    network_mode: "doll-report"
    volumes:
      - "/opt/doll.report.nginx.conf:/etc/nginx/nginx.conf"
      - "/opt/doll-report-static:/static"
      - "/opt/doll.report.nginx.conf.d:/etc/nginx/conf.d"
    ports:
      - "127.0.0.1:8081:80"
