name: lint ansible

on:
  push:

jobs:
  lint:
    if: ${{ github.ref != 'refs/heads/main' }}
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main # or vX.X.X version
        with:
          setup_python: "true"
          python_version: "3.14"
          requirements_file: "requirements.yml"
