---
name: Yaml Lint
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
  config-verify:
    needs: yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26'
          cache: true
          cache-dependency-path: 'scripts/go.sum'
      - run: |
          cd scripts
          go build validate-config.go
      - run: |
          set -e
          for file in ./dashboards/*.yaml; do
            echo Checking $file
            cat $file | grep '${' | awk '{ print $2 }' | sed -e 's_${__' | sed -e 's_}__' | awk '{ print "export " $1 "=http://invalid" }' > shimed_secrets
            source shimed_secrets
            ./scripts/validate-config $file
          done
